from __future__ import annotations

import re

from ..models import Request, Response, WafDetection

# WAF signatures list: (name, vendor, header_rules, cookie_rules, body_rules, blocked_rules)
WAF_RULES = [
    {
        "name": "Cloudflare",
        "vendor": "Cloudflare, Inc.",
        "headers": [
            ("cf-ray", re.compile(r".+")),
            ("cf-cache-status", re.compile(r".+")),
            ("cf-mitigated", re.compile(r".+")),
            ("server", re.compile(r"^cloudflare", re.IGNORECASE)),
        ],
        "cookies": [
            re.compile(r"^cf_clearance$", re.IGNORECASE),
            re.compile(r"^__cf_bm$", re.IGNORECASE),
            re.compile(r"^__cfduid$", re.IGNORECASE),
        ],
        "body": [
            re.compile(r"Attention Required!\s*\|\s*Cloudflare", re.IGNORECASE),
            re.compile(r"Cloudflare Ray ID:", re.IGNORECASE),
            re.compile(r"challenges\.cloudflare\.com", re.IGNORECASE),
            re.compile(r"error code:\s*1020", re.IGNORECASE),
        ],
    },
    {
        "name": "AWS WAF / CloudFront",
        "vendor": "Amazon Web Services",
        "headers": [
            ("x-amzn-requestid", re.compile(r".+")),
            ("x-amz-cf-id", re.compile(r".+")),
            ("x-amzn-waf-action", re.compile(r".+")),
            ("server", re.compile(r"^(?:awselb|cloudfront)", re.IGNORECASE)),
        ],
        "cookies": [
            re.compile(r"^aws-waf-token$", re.IGNORECASE),
            re.compile(r"^AWSALB$", re.IGNORECASE),
            re.compile(r"^AWSALBCORS$", re.IGNORECASE),
        ],
        "body": [
            re.compile(r"Generated by cloudfront \(CloudFront\)", re.IGNORECASE),
            re.compile(r"<H1>403 Forbidden</H1>\s*Request blocked\.", re.IGNORECASE),
            re.compile(r"AWS WAF", re.IGNORECASE),
        ],
    },
    {
        "name": "Akamai Kona Site Defender",
        "vendor": "Akamai Technologies",
        "headers": [
            ("x-akamai-transformed", re.compile(r".+")),
            ("akamai-grn", re.compile(r".+")),
            ("x-akamai-request-id", re.compile(r".+")),
            ("server", re.compile(r"^(?:AkamaiGHost|akamainetstorage)", re.IGNORECASE)),
        ],
        "cookies": [
            re.compile(r"^ak_bmsc$", re.IGNORECASE),
            re.compile(r"^bm_sz$", re.IGNORECASE),
            re.compile(r"^bm_sv$", re.IGNORECASE),
            re.compile(r"^bm_mi$", re.IGNORECASE),
        ],
        "body": [
            re.compile(r"Reference&#32;&#35;[0-9a-f.]+", re.IGNORECASE),
            re.compile(r"Access Denied.*You don't have permission to access", re.IGNORECASE),
            re.compile(r"AkamaiGHost", re.IGNORECASE),
        ],
    },
    {
        "name": "Imperva Incapsula",
        "vendor": "Imperva, Inc.",
        "headers": [
            ("x-iinfo", re.compile(r".+")),
            ("x-cdn", re.compile(r"Incapsula", re.IGNORECASE)),
            ("x-incap-sess", re.compile(r".+")),
        ],
        "cookies": [
            re.compile(r"^incap_ses_", re.IGNORECASE),
            re.compile(r"^visid_incap_", re.IGNORECASE),
            re.compile(r"^nlbi_", re.IGNORECASE),
        ],
        "body": [
            re.compile(r"Incapsula incident ID", re.IGNORECASE),
            re.compile(r"powered by Incapsula", re.IGNORECASE),
            re.compile(r"Request unsuccessful\. Incapsula", re.IGNORECASE),
            re.compile(r"_Incapsula_Resource", re.IGNORECASE),
        ],
    },
    {
        "name": "ModSecurity",
        "vendor": "Trustwave / OWASP",
        "headers": [
            ("server", re.compile(r"mod_security", re.IGNORECASE)),
            ("server", re.compile(r"NOYB-Shield", re.IGNORECASE)),
        ],
        "cookies": [],
        "body": [
            re.compile(r"This error was generated by Mod_Security", re.IGNORECASE),
            re.compile(r"Protected by ModSecurity", re.IGNORECASE),
            re.compile(r"mod_security-message", re.IGNORECASE),
        ],
    },
    {
        "name": "F5 BIG-IP ASM",
        "vendor": "F5 Networks",
        "headers": [
            ("server", re.compile(r"^(?:BigIP|BIG-IP)", re.IGNORECASE)),
            ("x-cnection", re.compile(r"close", re.IGNORECASE)),
        ],
        "cookies": [
            re.compile(r"^TS[0-9a-f]{8}$", re.IGNORECASE),
            re.compile(r"^TS01[0-9a-f]+$", re.IGNORECASE),
            re.compile(r"^BigIP$", re.IGNORECASE),
            re.compile(r"^MRHSession$", re.IGNORECASE),
        ],
        "body": [
            re.compile(r"The requested URL was rejected\. Please consult with your administrator\.", re.IGNORECASE),
            re.compile(r"Your support ID is:\s*<", re.IGNORECASE),
        ],
    },
    {
        "name": "Sucuri CloudProxy",
        "vendor": "Sucuri (GoDaddy)",
        "headers": [
            ("x-sucuri-id", re.compile(r".+")),
            ("x-sucuri-cache", re.compile(r".+")),
            ("server", re.compile(r"^Sucuri/Cloudproxy", re.IGNORECASE)),
        ],
        "cookies": [
            re.compile(r"^sucuri_cloudproxy_uuid_", re.IGNORECASE),
        ],
        "body": [
            re.compile(r"Access Denied\s*-\s*Sucuri Website Firewall", re.IGNORECASE),
            re.compile(r"Questions\?\s*admin@sucuri\.net", re.IGNORECASE),
            re.compile(r"Sucuri WebSite Firewall\s*-\s*CloudProxy", re.IGNORECASE),
        ],
    },
    {
        "name": "Signal Sciences (Fastly Next-Gen WAF)",
        "vendor": "Fastly, Inc.",
        "headers": [
            ("x-sigsci-request-id", re.compile(r".+")),
            ("x-sigsci-tags", re.compile(r".+")),
            ("x-fastly-request-id", re.compile(r".+")),
        ],
        "cookies": [],
        "body": [
            re.compile(r"Signal Sciences", re.IGNORECASE),
            re.compile(r"Fastly error: unknown domain", re.IGNORECASE),
        ],
    },
    {
        "name": "Microsoft Azure Front Door / AppGW WAF",
        "vendor": "Microsoft",
        "headers": [
            ("x-azure-ref", re.compile(r".+")),
            ("x-ms-ref", re.compile(r".+")),
            ("azure-waf-action", re.compile(r".+")),
        ],
        "cookies": [],
        "body": [
            re.compile(r"Our services aren't available right now", re.IGNORECASE),
            re.compile(r"Microsoft Azure Web Application Firewall", re.IGNORECASE),
        ],
    },
    {
        "name": "Fortinet FortiWeb",
        "vendor": "Fortinet, Inc.",
        "headers": [
            ("server", re.compile(r"FortiWeb", re.IGNORECASE)),
        ],
        "cookies": [
            re.compile(r"^FORTIWAFSID$", re.IGNORECASE),
        ],
        "body": [
            re.compile(r"FortiWeb Protection", re.IGNORECASE),
            re.compile(r"URL Blocked by FortiWeb", re.IGNORECASE),
        ],
    },
    {
        "name": "Barracuda WAF",
        "vendor": "Barracuda Networks",
        "headers": [
            ("server", re.compile(r"^Barracuda", re.IGNORECASE)),
        ],
        "cookies": [
            re.compile(r"^barra_counter_session$", re.IGNORECASE),
            re.compile(r"^BNI__BARRACUDA", re.IGNORECASE),
            re.compile(r"^BNI_persistence$", re.IGNORECASE),
        ],
        "body": [
            re.compile(r"You have been blocked by Barracuda", re.IGNORECASE),
            re.compile(r"Barracuda Networks", re.IGNORECASE),
        ],
    },
    {
        "name": "Wordfence Security",
        "vendor": "Defiant Inc.",
        "headers": [],
        "cookies": [
            re.compile(r"^wfvt_", re.IGNORECASE),
            re.compile(r"^wordfence_verifiedHuman$", re.IGNORECASE),
        ],
        "body": [
            re.compile(r"Generated by Wordfence", re.IGNORECASE),
            re.compile(r"Your access to this site has been limited at this time", re.IGNORECASE),
            re.compile(r"This response was generated by Wordfence", re.IGNORECASE),
        ],
    },
    {
        "name": "Radware AppWall",
        "vendor": "Radware",
        "headers": [
            ("x-sl-compstate", re.compile(r".+")),
        ],
        "cookies": [],
        "body": [
            re.compile(r"Unauthorized Activity Has Been Detected", re.IGNORECASE),
        ],
    },
    {
        "name": "Wallarm WAF",
        "vendor": "Wallarm, Inc.",
        "headers": [
            ("server", re.compile(r"nginx-wallarm", re.IGNORECASE)),
        ],
        "cookies": [],
        "body": [
            re.compile(r"nginx-wallarm", re.IGNORECASE),
        ],
    },
    {
        "name": "StackPath / MaxCDN",
        "vendor": "StackPath, LLC",
        "headers": [
            ("x-sp-waf", re.compile(r".+")),
            ("server", re.compile(r"^StackPath", re.IGNORECASE)),
        ],
        "cookies": [],
        "body": [],
    },
]

BLOCK_INDICATORS = [
    re.compile(r"access denied", re.IGNORECASE),
    re.compile(r"request blocked", re.IGNORECASE),
    re.compile(r"blocked by", re.IGNORECASE),
    re.compile(r"forbidden", re.IGNORECASE),
    re.compile(r"attention required", re.IGNORECASE),
    re.compile(r"security incident", re.IGNORECASE),
    re.compile(r"web application firewall", re.IGNORECASE),
    re.compile(r"the requested url was rejected", re.IGNORECASE),
    re.compile(r"support id is", re.IGNORECASE),
    re.compile(r"unauthorized activity has been detected", re.IGNORECASE),
]


def detect_waf(response: Response, request: Request | None = None) -> list[WafDetection]:
    """Inspect response headers, cookies, and body to identify active WAF / CDN shields."""
    results: list[WafDetection] = []
    body = response.body or ""
    headers_dict = {h.name.lower(): h.value for h in response.headers}

    cookie_names = [c.name for c in response.set_cookies]
    for h in response.headers:
        if h.name.lower() == "set-cookie":
            cname = h.value.split(";", 1)[0].split("=", 1)[0].strip()
            if cname and cname not in cookie_names:
                cookie_names.append(cname)

    is_block_status = response.status_code in (403, 406, 429, 503)
    has_block_body = any(p.search(body) for p in BLOCK_INDICATORS)
    is_blocked_page = is_block_status and has_block_body

    for rule in WAF_RULES:
        name = rule["name"]
        vendor = rule["vendor"]
        evidences: list[str] = []
        confidence_points = 0

        # Check headers
        for h_name, pat in rule["headers"]:
            if h_name in headers_dict:
                val = headers_dict[h_name]
                if pat.search(val):
                    evidences.append(f"Header '{h_name}: {val}'")
                    confidence_points += 2

        # Check cookies
        for pat in rule["cookies"]:
            for cname in cookie_names:
                if pat.search(cname):
                    evidences.append(f"Cookie '{cname}'")
                    confidence_points += 2

        # Check body patterns
        if body:
            for pat in rule["body"]:
                m = pat.search(body)
                if m:
                    snippet = m.group(0)[:60].replace("\n", " ").strip()
                    evidences.append(f"Body '{snippet}'")
                    confidence_points += 3

        if confidence_points > 0:
            confidence = "high" if confidence_points >= 2 else "medium"
            results.append(
                WafDetection(
                    name=name,
                    vendor=vendor,
                    confidence=confidence,
                    evidence=", ".join(evidences),
                    blocked=is_blocked_page,
                )
            )

    return sorted(results, key=lambda w: (w.confidence != "high", w.name))
