"""OpenAPI 3.0 Specification generator from discovered endpoints and request history.

Converts Darco's SiteMap (endpoints, forms, params) and recorded HTTP history
into a standard OpenAPI 3.0.3 specification that can be imported directly
into Postman, Burp Suite, OWASP ZAP, Caido, or API testing tools.
"""

from __future__ import annotations

import json
from typing import Any
from urllib.parse import urlsplit

import yaml

from .models import BodyType, HistoryRecord, SiteMap


def _clean_path(url: str, base_url: str) -> str:
    if url.startswith(base_url):
        p = url[len(base_url) :]
    else:
        p = urlsplit(url).path
    if not p or not p.startswith("/"):
        p = "/" + p
    return p.split("?")[0]


def _infer_schema_from_obj(val: Any) -> dict[str, Any]:
    if isinstance(val, bool):
        return {"type": "boolean", "example": val}
    if isinstance(val, int):
        return {"type": "integer", "example": val}
    if isinstance(val, float):
        return {"type": "number", "example": val}
    if isinstance(val, str):
        return {"type": "string", "example": val}
    if isinstance(val, list):
        item_schema = _infer_schema_from_obj(val[0]) if val else {"type": "string"}
        return {"type": "array", "items": item_schema}
    if isinstance(val, dict):
        props = {}
        for k, v in val.items():
            props[k] = _infer_schema_from_obj(v)
        return {"type": "object", "properties": props}
    return {"type": "string"}


def export_openapi(
    sitemap: SiteMap | None = None,
    history: list[HistoryRecord] | None = None,
    target_url: str = "",
    title: str = "Darco Discovered API",
    version: str = "1.0.0",
    as_yaml: bool = False,
) -> dict[str, Any] | str:
    """Generate an OpenAPI 3.0.3 specification dictionary or YAML string."""
    base_target = target_url
    if not base_target and sitemap and sitemap.target:
        base_target = sitemap.target
    elif not base_target and history and history[0].request.url:
        base_target = history[0].request.url

    split = urlsplit(base_target if "://" in base_target else "http://" + base_target)
    server_base = f"{split.scheme or 'http'}://{split.netloc}"

    spec: dict[str, Any] = {
        "openapi": "3.0.3",
        "info": {
            "title": title,
            "version": version,
            "description": "Generated by Darco HTTP Security Toolkit.",
        },
        "servers": [{"url": server_base}],
        "paths": {},
    }

    paths = spec["paths"]

    # 1. Populate from SiteMap endpoints & forms
    if sitemap:
        for ep in sitemap.endpoints:
            rel_path = _clean_path(ep.url, server_base)
            if rel_path not in paths:
                paths[rel_path] = {}

            methods = [m.lower() for m in ep.methods] or ["get"]
            for m in methods:
                op: dict[str, Any] = {
                    "summary": f"{m.upper()} {rel_path}",
                    "operationId": f"{m}_{rel_path.replace('/', '_').strip('_') or 'root'}",
                    "parameters": [],
                    "responses": {
                        str(ep.status or 200): {
                            "description": "Observed endpoint response"
                        }
                    },
                }
                # Query parameters
                for p in ep.params:
                    op["parameters"].append(
                        {
                            "name": p.name,
                            "in": "query",
                            "required": False,
                            "schema": _infer_schema_from_obj(p.value),
                        }
                    )
                paths[rel_path][m] = op

        for form in sitemap.forms:
            form_url = form.action or sitemap.target
            rel_path = _clean_path(form_url, server_base)
            if rel_path not in paths:
                paths[rel_path] = {}

            method = (form.method or "POST").lower()
            props = {}
            for inp in form.inputs:
                if inp.name:
                    props[inp.name] = {"type": "string", "example": inp.default or ""}

            op = {
                "summary": f"{method.upper()} {rel_path} (Form)",
                "operationId": f"{method}_{rel_path.replace('/', '_').strip('_')}_form",
                "requestBody": {
                    "content": {
                        "application/x-www-form-urlencoded": {
                            "schema": {
                                "type": "object",
                                "properties": props,
                            }
                        }
                    }
                },
                "responses": {"200": {"description": "Form submission response"}},
            }
            paths[rel_path][method] = op

    # 2. Enrich from recorded request/response history
    if history:
        for rec in history:
            req = rec.request
            resp = rec.response
            rel_path = _clean_path(req.url, server_base)
            if rel_path not in paths:
                paths[rel_path] = {}

            method = req.method.lower()
            if method not in paths[rel_path]:
                paths[rel_path][method] = {
                    "summary": f"{req.method} {rel_path}",
                    "operationId": f"{method}_{rel_path.replace('/', '_').strip('_') or 'root'}",
                    "parameters": [],
                    "responses": {},
                }

            op = paths[rel_path][method]

            # Query params
            existing_params = {p["name"] for p in op.get("parameters", [])}
            for p in req.params:
                if p.name not in existing_params:
                    op["parameters"].append(
                        {
                            "name": p.name,
                            "in": "query",
                            "required": False,
                            "schema": _infer_schema_from_obj(p.value),
                        }
                    )
                    existing_params.add(p.name)

            # Request body
            if req.body_type == BodyType.JSON and req.body_json is not None:
                op["requestBody"] = {
                    "content": {
                        "application/json": {
                            "schema": _infer_schema_from_obj(req.body_json)
                        }
                    }
                }
            elif req.body_type == BodyType.FORM and req.body_form:
                props = {p.name: {"type": "string", "example": p.value} for p in req.body_form}
                op["requestBody"] = {
                    "content": {
                        "application/x-www-form-urlencoded": {
                            "schema": {"type": "object", "properties": props}
                        }
                    }
                }

            # Response status code
            if resp:
                status_str = str(resp.status_code)
                resp_obj: dict[str, Any] = {"description": resp.reason or f"HTTP {status_str}"}
                ctype = next((h.value for h in resp.headers if h.name.lower() == "content-type"), "")
                if "json" in ctype and resp.body:
                    try:
                        j_body = json.loads(resp.body)
                        resp_obj["content"] = {
                            "application/json": {
                                "schema": _infer_schema_from_obj(j_body)
                            }
                        }
                    except (ValueError, json.JSONDecodeError):
                        pass
                op["responses"][status_str] = resp_obj

    if as_yaml:
        return yaml.dump(spec, sort_keys=False)
    return spec
